version: "3.8"

services:
  # Infrastructure as Code
  terraform-lab:
    image: hashicorp/terraform:latest
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - terraform_data:/root/.terraform
      - ./terraform:/terraform
    networks:
      - devops

  # Database per Harbor
  postgresql:
    image: postgres:13
    environment:
      POSTGRES_DB: registry
      POSTGRES_USER: harbor
      POSTGRES_PASSWORD: harbor123
    volumes:
      - harbor_postgres_data:/var/lib/postgresql/data
    networks:
      - devops

  # Container Registry
  harbor:
    image: goharbor/harbor-core:v2.5.0
    environment:
      - POSTGRESQL_HOST=postgresql
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_USERNAME=harbor
      - POSTGRESQL_PASSWORD=harbor123
      - POSTGRESQL_DATABASE=registry
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.services.registry-${STACK}.loadbalancer.server.port=80
        - traefik.http.routers.registry-${STACK}.rule=PathPrefix(`/`)
    volumes:
      - harbor_data:/data
    networks:
      - devops

  # CI/CD
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
    command: ["sh", "-c", "java -jar /usr/share/jenkins/jenkins.war --prefix=/jenkins"]
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.services.jenkins-${STACK}.loadbalancer.server.port=8080
        - traefik.http.routers.jenkins-${STACK}.rule=PathPrefix(`/jenkins`)
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - devops

  # GitLab
  gitlab:
    image: gitlab/gitlab-ce:latest
    environment:
      - GITLAB_RELATIVE_URL_ROOT=/gitlab
    command: ["sh", "-c", "export GITLAB_RELATIVE_URL_ROOT=/gitlab && /assets/wrapper"]
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.services.gitlab-${STACK}.loadbalancer.server.port=80
        - traefik.http.routers.gitlab-${STACK}.rule=PathPrefix(`/gitlab`)
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_data:/var/opt/gitlab
    networks:
      - devops

  # Monitoring
  prometheus:
    image: prom/prometheus:latest
    command: ["--web.external-url=/prometheus"]
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.services.prometheus-${STACK}.loadbalancer.server.port=9090
        - traefik.http.routers.prometheus-${STACK}.rule=PathPrefix(`/prometheus`)
    volumes:
      - prometheus_data:/prometheus
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.services.grafana-${STACK}.loadbalancer.server.port=3000
        - traefik.http.routers.grafana-${STACK}.rule=PathPrefix(`/grafana`)
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitoring

  # Logging
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      - discovery.type=single-node
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - logging

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.0
    environment:
      - SERVER_BASEPATH=/kibana
      - SERVER_REWRITEBASEPATH=true
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.services.kibana-${STACK}.loadbalancer.server.port=5601
        - traefik.http.routers.kibana-${STACK}.rule=PathPrefix(`/kibana`)
    networks:
      - logging

  # Load Testing
  k6:
    image: loadimpact/k6:latest
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - ./k6-scripts:/scripts
    networks:
      - devops

  # Reverse Proxy
  traefik:
    image: traefik:v2.10
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.swarmMode=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - devops
      - monitoring
      - logging
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`)
        - traefik.http.routers.traefik.service=api@internal
        - traefik.http.services.traefik.loadbalancer.server.port=8080

networks:
  devops:
    driver: overlay
  monitoring:
    driver: overlay
  logging:
    driver: overlay

volumes:
  terraform_data:
  harbor_data:
  harbor_postgres_data:
  jenkins_home:
  gitlab_config:
  gitlab_data:
  prometheus_data:
  grafana_data:
  elasticsearch_data:
